/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CAL_H_RPCGEN
#define _CAL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct X_vec {
	int n;
	struct {
		u_int X_len;
		int *X_val;
	} X;
};
typedef struct X_vec X_vec;

struct product {
	int n;
	struct {
		u_int X_len;
		int *X_val;
	} X;
	struct {
		u_int Y_len;
		int *Y_val;
	} Y;
};
typedef struct product product;

struct mean {
	int n;
	struct {
		u_int X_len;
		int *X_val;
	} X;
	struct {
		u_int Y_len;
		int *Y_val;
	} Y;
};
typedef struct mean mean;

struct r_product {
	int n;
	float r;
	struct {
		u_int X_len;
		int *X_val;
	} X;
	struct {
		u_int Y_len;
		int *Y_val;
	} Y;
};
typedef struct r_product r_product;

struct mean_table {
	struct {
		u_int XY_len;
		float *XY_val;
	} XY;
};
typedef struct mean_table mean_table;

struct product_table {
	struct {
		u_int rXY_len;
		float *rXY_val;
	} rXY;
};
typedef struct product_table product_table;

#define CAL_PROG 0x23451111
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define mangi 1
extern  float * mangi_1(X_vec *, CLIENT *);
extern  float * mangi_1_svc(X_vec *, struct svc_req *);
#define X_Y 2
extern  int * x_y_1(product *, CLIENT *);
extern  int * x_y_1_svc(product *, struct svc_req *);
#define cal_mean 3
extern  mean_table * cal_mean_1(mean *, CLIENT *);
extern  mean_table * cal_mean_1_svc(mean *, struct svc_req *);
#define r_XY 4
extern  product_table * r_xy_1(r_product *, CLIENT *);
extern  product_table * r_xy_1_svc(r_product *, struct svc_req *);
extern int cal_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define mangi 1
extern  float * mangi_1();
extern  float * mangi_1_svc();
#define X_Y 2
extern  int * x_y_1();
extern  int * x_y_1_svc();
#define cal_mean 3
extern  mean_table * cal_mean_1();
extern  mean_table * cal_mean_1_svc();
#define r_XY 4
extern  product_table * r_xy_1();
extern  product_table * r_xy_1_svc();
extern int cal_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_X_vec (XDR *, X_vec*);
extern  bool_t xdr_product (XDR *, product*);
extern  bool_t xdr_mean (XDR *, mean*);
extern  bool_t xdr_r_product (XDR *, r_product*);
extern  bool_t xdr_mean_table (XDR *, mean_table*);
extern  bool_t xdr_product_table (XDR *, product_table*);

#else /* K&R C */
extern bool_t xdr_X_vec ();
extern bool_t xdr_product ();
extern bool_t xdr_mean ();
extern bool_t xdr_r_product ();
extern bool_t xdr_mean_table ();
extern bool_t xdr_product_table ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CAL_H_RPCGEN */
