/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cal.h"
#include <math.h>
float *
mangi_1_svc(X_vec *argp, struct svc_req *rqstp)
{
	static float  result;

    printf("Calculate the Magnitude of Vector X.");
	float temp=0;
	result=0;
	for (int i = 0; i < argp->n; i++) {
		result = pow(argp->X.X_val[i],2) + result;
		// result = result +temp;
    }
	result = sqrt(result);
	return &result;
}

int *
x_y_1_svc(product *argp, struct svc_req *rqstp)
{
	static int  result;
	int temp;
	result= 0;
    printf("Inner product of Vector X and Y.");
    for (int i = 0; i <argp->n; i++) {
        temp = argp->X.X_val[i] * argp->Y.Y_val[i];
		result = result +temp;
    }

	return &result;
}

mean_table *
cal_mean_1_svc(mean *argp, struct svc_req *rqstp)
{
	static mean_table  result;
	int sum=0;
	float meanX,meanY;
    printf("Calculate the mean of Vector X and Y.");
	result.XY.XY_len=2;
	result.XY.XY_val=(float *)malloc(2*sizeof(float));

    for (int i = 0; i < argp->n; i++) {
        sum = sum +argp->X.X_val[i];
    }

	meanX = sum/argp->n;

	sum=0;

	for (int i = 0; i < argp->n; i++) {
		sum = sum + argp->Y.Y_val[i];
	}
	meanY = sum/argp->n;
	result.XY.XY_val[0]=meanX;
	result.XY.XY_val[1]=meanY;

	return &result;
}

product_table *
r_xy_1_svc(r_product *argp, struct svc_req *rqstp)
{
	static product_table  result;
	printf("Calculate the product of r*(X + Y).");

	result.rXY.rXY_len=argp->n;
	result.rXY.rXY_val=(float *)malloc(argp->n*sizeof(float));

	for (int i = 0; i <argp->n; i++) {
        result.rXY.rXY_val[i] = argp->X.X_val[i] + argp->Y.Y_val[i];
    }

	for (int i = 0; i < argp->n; i++) {
		result.rXY.rXY_val[i] =argp->r*result.rXY.rXY_val[i];
	}

	return &result;
}
